import type { Metadata } from 'next'
import { Geist_Mono, Oswald } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'
import { WorkoutProvider } from '@/context/PlanContext'
import { ToastContainer } from 'react-toastify'

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={`${oswald.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <WorkoutProvider>
          <ToastContainer />
          <Navbar />
          <main className='flex-1'>{children}</main>
          <Footer />
        </WorkoutProvider>
      </body>
    </html>
  )
}
